### ISSUE TITLE
Struggling to use Mediapipe with tensorflow/cuda following install instructions

### ISSUE THREAD

**Issue by Hakazaba** [google/mediapipe#1400]
I have spent a month trying to get mediapipe working, following the installation instructions for using gpu, however it seems somewhat vague or outdated. 
Setting python 3.7 as the default on ubuntu will break apt, however i am using pyenv for this, im not sure if this is a problem or not, it is not explained in the installation material how to prepare this for mediapipe correctly.

Are we meant to build tensorflow from source, through pip or use a docker image? If built, what settings should we be using?
This is pursued on the assumption that cuda inference is used to gain better performance or accuracy? 
Is this true or is it better to use opengl?

The current tensorflow version uses cuda 11.0, the installation describes using 10.1. 

If using pip to install tensorflow,there is no .bazelrc file to copy from. Using the described expected code and replacing instances of 10.1 with 11.0 a build of: 

````
bazel build -c opt --config=cuda --spawn_strategy=local   --verbose_failures   --define no_aws_support=true --copt -DMESA_EGL_NO_X11_HEADERS     mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu

...

ERROR: /root/mediapipe/mediapipe/framework/tool/BUILD:66:10: Linking of rule '//mediapipe/framework/tool:encode_as_c_string' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/c14cf19f75c61ffdb03065b678c7c641/execroot/mediapipe && \
  exec env - \
    PATH=/root/.pyenv/shims:/root/.pyenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
    PWD=/proc/self/cwd \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc @bazel-out/host/bin/mediapipe/framework/tool/encode_as_c_string-2.params)
Execution platform: @local_execution_config_platform//:platform
/usr/bin/ld: bazel-out/host/bin/external/com_google_absl/absl/strings/libstrings.a(charconv.o): undefined reference to symbol 'nan@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu failed to build
````

I've explored multiple solutions and have completely reformatted my machine over 10 times in trying to get mediapipe working with cuda, please help.
I need more guidance to install this correctly. Or should i just use OpenGL ES?

**Comment by jiuqiant** [comment]
TensorFlow GPU adn TFLite GPU are different -- TensorFlow GPU is on cuda and TFLite GPU is on OpenGL ES.
Most mediapipe demos including hand tracking gpu are with TFLite and OpenGL ES.
Unless you plan to run your own TensorFlow model on GPU with MediaPipe, you don't need to setup cuda. Also, the issue you reported is more likely due to the incompatibility between absl and your compiler.

**Comment by Hakazaba** [comment]
I thought i would be able to run mediapipe models through tensorflow cuda. Well, ill give up on using Cuda for now then. Though tensorflow has a really nice implimentation of iris and face which mediapipe lacks. Both work separately form eachother for me too, so its fairly odd for an incompatibilty like this. I have no idea what absl is though.

**Comment by sgowroji** [comment]
Hi @Hakazaba, You can check the latest documentation related to the [CUDA](https://google.github.io/mediapipe/getting_started/gpu_support.html#tensorflow-cuda-support-and-setup-on-linux-desktop) and reach us if your still facing any problem through it.

**Comment by sgowroji** [comment]
Hi @Hakazaba, Could you please respond if you still looking resolution for the above query. Thanks!

**Comment by ueihgnurt** [comment]
> Hi @Hakazaba, Could you please respond if you still looking resolution for the above query. Thanks!

Nothing change. Here the review. Each one need to add linkopts -lm so that it can get cmath library. Also I received libffi error 「undefined symbol: ffi_type_uint32, version LIBFFI_BASE_7.0」 after I added all linkopts in the programs both in Conda or not in conda env. As result need to init LD_PRELOAD=/usr/lib/{os}-linux-gnu/libffi.so.7. Then I realise it get ignored and need LD_DEBUG to run it. Then got ton of error related to other symlink. CUDA support is too old and need update.
OpenCL a better choice.
