### ISSUE TITLE
Creating an Xcode Project for Xcode 11.3.1

### ISSUE THREAD

**Issue by Amacelia** [google/mediapipe#537]
Been following the setup, https://github.com/google/mediapipe/blob/master/mediapipe/docs/mediapipe_ios_setup.md 
Ran into an error when running 
`sh build_and_run.sh`

Here's some output:
```
ERROR: /FAKEPATH/tulsi/BUILD:62:1: Linking of rule '//:tulsi.__internal__.apple_binary' failed (Exit 1) wrapped_clang failed: error executing command external/local_config_cc/wrapped_clang -Xlinker -objc_abi_version -Xlinker 2 -fobjc-link-runtime -ObjC -arch x86_64 -filelist ... (remaining 26 argument(s) skipped)
...

Undefined symbols for architecture x86_64:
  "static Foundation.CharacterSet.whitespaces.getter : Foundation.CharacterSet", referenced from:
      closure #2 (Swift.String) -> Swift.String in TulsiGenerator.PBXTargetGenerator.(addConfigsForIndexingTarget in _9BC2D135E4F1D200D8B700936548BDC4)(_: TulsiGenerator.PBXTarget, data: TulsiGenerator.PBXTargetGenerator.(IndexerData in _9BC2D135E4F1D200D8B700936548BDC4)) -> () in libtulsi_generator_lib.a(PBXTargetGenerator.swift_c4dad555e799e0fd73717303c2484870.o)
      (extension in TulsiGenerator):Swift.String.escapingForShell.getter : Swift.String in libtulsi_generator_lib.a(StringExtensions.swift_85a5559263c23a693d91459f1d9e7796.o)
      closure #1 (TulsiGenerator.ProcessRunner.CompletionInfo) -> () in TulsiGenerator.XcodeProjectGenerator.(executePythonProcess in _3D27909A8CA7F8C4C4BE25046CB74F8B)(_: Swift.String, onError: (Swift.Int32, Swift.String) -> ()) -> () in libtulsi_generator_lib.a(XcodeProjectGenerator.swift_75b418efaa20bf820b085a94e9634ba3.o)
...

ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //:tulsi failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 50.516s, Critical Path: 32.89s
INFO: 38 processes: 25 darwin-sandbox, 13 local.
FAILED: Build did NOT complete successfully

```

Any suggestions on what to do to create an Xcode project with this?

**Comment by 7AM7** [comment]
Same here

**Comment by 7AM7** [comment]
Everything working fine with me now with Xcode 11.3.1 [Photo](https://imgur.com/6IVRatk) :
some tips :
In `tulsi/WORKSPACE` you need to change 
```
git_repository(
 
)

```
by 
```

git_repository(
    name = "build_bazel_rules_apple",
    remote = "https://github.com/bazelbuild/rules_apple.git",
    tag = "0.19.0",
)

```

In `.bazelrc `you need to change the version of Xcode
`build --xcode_version=11.2.1`
to
`build --xcode_version=11.3.1`
Then go ahead with  following the setup, https://github.com/google/mediapipe/blob/master/mediapipe/docs/mediapipe_ios_setup.md

**Comment by Amacelia** [comment]
Thanks! 
I have Xcode version 11.4 so I just put that and it worked. 

Tip: for Step 1 of "Creating an Xcode Project", you don't have to `git fetch` and `git checkout`

**Comment by athenason** [comment]
I modified git_repository and use --xcode_version=11.3.1
but I still got this error
/Downloads/mediapipe-github/tulsi/BUILD:61:1: Linking of rule '//:tulsi' failed (Exit 1) wrapped_clang failed: error executing command external/local_config_cc/wrapped_clang -Xlinker -objc_abi_version -Xlinker 2 -fobjc-link-runtime -ObjC -arch x86_64 -filelist ... (remaining 27 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Undefined symbols for architecture x86_64:
  "_swift_getFunctionReplacement", referenced from:
      _swift_getFunctionReplacement50 in libswiftCompatibilityDynamicReplacements.a(DynamicReplaceable.cpp.o)
     (maybe you meant: _swift_getFunctionReplacement50)
  "_swift_getOrigOfReplaceable", referenced from:
      _swift_getOrigOfReplaceable50 in libswiftCompatibilityDynamicReplacements.a(DynamicReplaceable.cpp.o)
     (maybe you meant: _swift_getOrigOfReplaceable50)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //:tulsi failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.257s, Critical Path: 0.18s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
