### ISSUE TITLE
 Compiling mediapipe/gpu/gl_texture_buffer.cc failed: (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt/bin/mediapipe/gpu/_objs/gl_texture_buffer/gl_texture_buffer.d

### ISSUE THREAD

**Issue by robi56** [google/mediapipe#3658]
**### Trying to build for ubunutu desktop MediaPIPE GPU** 

`bazel build -c opt --config=cuda --spawn_strategy=local     --define no_aws_support=true --copt -DMESA_EGL_NO_X11_HEADERS     mediapipe/examples/desktop/object_detection:object_detection_tensorflow`

**Error:** 

INFO: Analyzed target //mediapipe/examples/desktop/object_detection:object_detection_tensorflow (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/turing/GPU_MediaPIPE/mediapipe/mediapipe/gpu/BUILD:212:11: Compiling mediapipe/gpu/gl_texture_buffer.cc failed: (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt/bin/mediapipe/gpu/_objs/gl_texture_buffer/gl_texture_buffer.d ... (remaining 60 arguments skipped)
In file included from ./mediapipe/gpu/gl_texture_view.h:23:0,
                 from ./mediapipe/gpu/gl_texture_buffer.h:27,
                 from mediapipe/gpu/gl_texture_buffer.cc:15:
./mediapipe/gpu/gpu_buffer_storage.h: In instantiation of ‘mediapipe::internal::GpuBufferStorageRegistry::RegisterConverter(F&&)::<lambda(std::shared_ptr<mediapipe::internal::GpuBufferStorage>)> [with StorageFrom = mediapipe::GlTextureBuffer; StorageTo = mediapipe::GpuBufferStorageImageFrame; F = std::shared_ptr<mediapipe::GpuBufferStorageImageFrame> (&)(std::shared_ptr<mediapipe::GlTextureBuffer>)]’:
./mediapipe/gpu/gpu_buffer_storage.h:89:10:   required from ‘struct mediapipe::internal::GpuBufferStorageRegistry::RegisterConverter(F&&) [with StorageFrom = mediapipe::GlTextureBuffer; StorageTo = mediapipe::GpuBufferStorageImageFrame; F = std::shared_ptr<mediapipe::GpuBufferStorageImageFrame> (&)(std::shared_ptr<mediapipe::GlTextureBuffer>)]::<lambda(class std::shared_ptr<mediapipe::internal::GpuBufferStorage>)>’
./mediapipe/gpu/gpu_buffer_storage.h:93:60:   required from ‘mediapipe::internal::GpuBufferStorageRegistry::RegistryToken mediapipe::internal::GpuBufferStorageRegistry::RegisterConverter(F&&) [with StorageFrom = mediapipe::GlTextureBuffer; StorageTo = mediapipe::GpuBufferStorageImageFrame; F = std::shared_ptr<mediapipe::GpuBufferStorageImageFrame> (&)(std::shared_ptr<mediapipe::GlTextureBuffer>)]’
mediapipe/gpu/gl_texture_buffer.cc:355:32:   required from here
./mediapipe/gpu/gpu_buffer_storage.h:90:50: error: variable ‘converter’ has function type
             -> std::shared_ptr<GpuBufferStorage> {
                                                  ^
./mediapipe/gpu/gpu_buffer_storage.h:90:50: error: variable ‘converter’ has function type

**Comment by kuaashish** [comment]
Hi @robi56, Could you try to upgrade the gcc version to gcc9.4.0 as "[converter](std::shared_ptr source)......" only supports the higher gcc version. 
Please refer to https://gcc.gnu.org/projects/cxx-status.html#cxx17 and https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0512r0.pdf for better understanding.
Thank you!

**Comment by WangXuan2401** [comment]
Well, the error  still occur after I updating the gcc version to 9.4.0.
Is there any missing procedures ?

**Comment by kuaashish** [comment]
Hi @WangXuan2401, 
Could you please raise a new issue with complete details and steps to reproduce the issue from our end. 
Thank you!
