### ISSUE TITLE
Error in multi_hand_tracking_desktop

### ISSUE THREAD

**Issue by bluesky0960** [google/mediapipe#747]
For reference, the hello_world_desktop file works correctly. However, when I attempt to run the multi_hand_tracking_desktop and face_detection_desktop file for CPU, I got same error from both of them:

**Ubuntu Version**
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

**Bazel Version**
Build label: 3.0.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Mon Apr 6 12:52:37 2020 (1586177557)
Build timestamp: 1586177557
Build timestamp as int: 1586177557

**Opencv Version**
4.3.0

**Command**
bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1
mediapipe/examples/desktop/multi_hand_tracking:multi_hand_tracking_cpu
bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1
mediapipe/examples/desktop/face_detection:face_detection_cpu

**Error**
INFO: Analyzed target //mediapipe/examples/desktop/multi_hand_tracking:multi_hand_tracking_cpu (7 packages loaded, 990 targets configured).
INFO: Found 1 target...
ERROR: /home/harry/mediapipe/mediapipe/examples/desktop/BUILD:37:1: C++ compilation of rule '//mediapipe/examples/desktop:demo_run_graph_main' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 62 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from mediapipe/examples/desktop/demo_run_graph_main.cc:25:0:
./mediapipe/framework/port/opencv_video_inc.h: In function 'cv::Ptr<cv::DenseOpticalFlow> cv::createOptFlow_DualTVL1()':
./mediapipe/framework/port/opencv_video_inc.h:92:19: error: 'createOptFlow_DualTVL1' is not a member of 'cv::optflow'
   return optflow::createOptFlow_DualTVL1();
                   ^~~~~~~~~~~~~~~~~~~~~~
./mediapipe/framework/port/opencv_video_inc.h:92:19: note: suggested alternative: 'createOptFlow_DIS'
   return optflow::createOptFlow_DualTVL1();
                   ^~~~~~~~~~~~~~~~~~~~~~
                   createOptFlow_DIS
Target //mediapipe/examples/desktop/multi_hand_tracking:multi_hand_tracking_cpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 4.961s, Critical Path: 3.00s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

**Comment by jiuqiant** [comment]
MediaPipe is currently with OpenCV 3. 

If you followed the step 3 option 3 of https://github.com/google/mediapipe/blob/master/mediapipe/docs/install.md#installing-on-debian-and-ubuntu to config opencv for MediaPipe, I believe it works with OpenCV 4.1. However, we can't guarantee that that setting works with every OpenCV 4 version.

**Comment by bluesky0960** [comment]
Thanks, I solved the problem when I worked with OpenCV 3.4
